bundle_path "vendor/bundler_gems"
source "http://gems.github.com"
source "http://gems.rubyforge.org"
source "http://gems.engineyard.com"
source "http://gems.rubyonrails.org"

gem "rake", "0.8.7"
gem "rails", "2.3.5"
gem "haml", "2.2.17"
gem "mysql", "2.8.1"