# This is a sample database file for the DataMapper ORM
:development: &defaults
  :adapter: mysql
  :database: dev_gostaberling
  :username: root
  :password:
  :host: localhost

:test:
  <<: *defaults
  :database: test_gostaberling

:demo:
  <<: *defaults
  :database: demo_gostaberling

:production:
  <<: *defaults
  :database: prod_gostaberling