generic: &generic
  adapter: mysql
  encoding: utf8
  username: root
  socket: /tmp/mysql.sock

development:
  database: gosta_dev
  password: password
  <<: *generic

test:
  database: gosta_test
  password: password
  <<: *generic

demo:
  database: gosta_demo
  password: iron8wine
  <<: *generic

production:
  database: gosta_prod
  password: iron8wine
  <<: *generic
