development:
  adapter: postgresql
  database: gostaberling_dev
  username: postgres
  password: postgres
  host: localhost

test:
  database: gostaberling_test

production:
  database: gostaberling_production
