generic: &generic
  adapter: mysql
  encoding: utf8
  username: root
  socket: /tmp/mysql.sock

development:
  database: dev_gostaberling
  password: password
  <<: *generic

test:
  database: test_gostaberling
  password: password
  <<: *generic

demo:
  database: demo_gostaberling
  password: iron8wine
  <<: *generic

production:
  database: prod_gostaberling
  password: iron8wine
  <<: *generic
